config/routes.rb
Mff::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'pages#content'
  
  resources :posts
  
  resources :messages # '/message/:id' => 'messages#new', :as => :message
  
  match ':slug' => 'pages#content', :as => :content

end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(128)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  # # send password reset instructions for new user
  # after_create { |admin| admin.send_reset_password_instructions }
  # 
  # # allow us to create new user without password
  # def password_required?
  #   new_record? ? false : super
  # end
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :integer         not null, primary key
#  message    :string(255)
#  status     :string(255)
#  ip         :string(255)
#  created_at :datetime
#  updated_at :datetime
#  from_email :string(255)
#  from_name  :string(255)
#

class Message < ActiveRecord::Base
  attr_accessor :form_name
  
  validates :message, :presence => true
  
  validates :from_email, :presence => true, :format => { 
    :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/, 
    :message => "is not a valid email."}
  
  validates :from_name, :presence => true
end

app/models/page.rb
# == Schema Information
#
# Table name: pages
#
#  id            :integer         not null, primary key
#  slug          :string(255)
#  content       :text(255)
#  created_at    :datetime
#  updated_at    :datetime
#  title         :string(255)
#  active        :boolean         default(TRUE)
#  display_order :integer         default(0)
#

class Page < ActiveRecord::Base
  scope :active, where(:active => true)

  validates :title,
    :presence => true,
    :length => { :maximum => 255 }

  validates :slug,
    :uniqueness => true,
    :presence => true,
    :length => { :maximum => 255 },
    :format => { :with => /^[a-z0-9-]+$/ }

  validates :display_order,
    :presence => true

  validates :content,
    :presence => true

  def self.content_page(slug)
    slug = slug ||= 'index'
    Page.active.where(:slug => slug).order("updated_at desc").first
  end

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  slug       :string(255)
#  active     :boolean
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  scope :active, where(:active => true).order("updated_at desc")

  validates :title,
    :presence => true,
    :length => { :maximum => 255 }

  validates :slug,
    :uniqueness => true,
    :presence => true,
    :length => { :maximum => 255 },
    :format => { :with => /^[a-z0-9-]+$/ }

  validates :content,
    :presence => true
    
  def self.get_all
    Post.active
  end
  
  def self.get(slug)
    Post.active.where(:slug => slug).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :page_links
  helper_method :posts
  
  def page_links
    Page.where(:active => true).order(:display_order)
  end
  
  def posts
    Post.active.order(:updated_at)
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  def show
    @message = Message.new(:form_name => params[:id])
  end
  
  def create
    @message = Message.new(params[:message])
    
    if @message.invalid? 
      render :action => 'show'
      return
    end
    
    @message.status = :new
    @message.ip = request.remote_ip
    
    if @message.save
      MessageMailer.mail_message(@message).deliver
      render 'thank_you'
    else
      render :action => 'show'
      flash[:notice] = 'Unable to send message. Please try again.'
    end
    
  end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # GET /:slug
  #
  def content
    @page = Page.content_page(params[:slug])
    raise ActionController::RoutingError.new('Not Found') if @page.nil?
    @title = @page.title
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.get_all
  end
  
  def show
    @post = Post.get params[:id]
    raise ActionController::RoutingError.new('Not Found') if @post.nil?
    @title = @post.title 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def active_page?(type, id)
    result = if type == :page
        (params[:id].nil? and params[:slug].nil? and id == 'index') or 
          params[:slug] == id
      elsif type == :message
        params[:id] === id
      else
        false
      end
  end
  
  
  def site_title
    base_title = Rails.application.config.site_title
    
    if(@title.nil?)
      return base_title
    end
    
    "#{base_title} | #{@title}"
  end
  
end

app/helpers/messages_helper.rb
module MessagesHelper


end

app/helpers/pages_helper.rb
module PagesHelper
  def title
    @page.title.blank? ? "Merrick Family Foundation" : "Merrick Family Foundation - #{@page.title}"
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/application/_aside.html.erb
<aside id="side-bar">
	<h2>Latest News</h2>
	<% aside.each do |item|%>
		<article>
			<div class="date"><%= item.updated_at.strftime("%m/%d/%Y") %></div>
			<div class="story">
				<%= raw truncate(item.content, :length => 250, :omission => "... #{link_to 'more', post_path(:id => item.slug) }", :separator => ' ' ) %>
			</div>
		</article>
	<% end %>
	<div class="widget-container" id="sharethis-widget">
		<div id="donate">
      <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
      <input type="hidden" name="cmd" value="_s-xclick">
      <input type="hidden" name="hosted_button_id" value="WHRUSLW8237N2">
      <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
      <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
      </form>
    </div>
		<%= render :partial => 'sharethis' %>		
		
	</div> 

</aside>

app/views/application/_footer.html.erb
<footer>
	<!-- <ul>
		<% footer.each do |item| %>
			<li>
			<%= link_to item.title, content_path(:slug => item.slug) %>
			</li>
		<% end %>
		<li><a href="<%= message_path :id => :contact %>">Apply</a></li>
		<li><a href="<%= message_path :id => :apply %>">Contact</a></li>
	</ul> -->
	<div id="legal">
		<span id="copyright"><span class="purple-txt">©</span> 2011  Merrick Family Foundation. All rights reserved.</span>
		<span id="address">PO Box 400 Essington, PA 19029</span> |
		<span id="phone">Phone: 610-583-9640</span> |
		<span id="phone">Email: info@merrickfamilyfoundation.org</span>
	</div>
</footer>
<%= debug(params) if Rails.env.development? %>

app/views/application/_nav.html.erb
<nav>
	<ul id="nav">
		<% nav.each do |item| %>
			<li class="<%= active_page?(:page, item.slug) ? 'current_page_item' : ''%>">
				<%= link_to item.title, content_path(:slug => item.slug) %>
			</li>
		<% end %>
		<!-- <li class="<%= active_page?(:message, 'apply') ? 'current_page_item' : ''%>">
		      <%= link_to 'Apply', message_path(:id => :apply) %>
		    </li> -->
		<li class="<%= active_page?(:message, 'contact') ? 'current_page_item' : ''%>">
			<%= link_to 'Contact', message_path(:id => :contact) %>

		</li>
	</ul>
</nav>

app/views/application/_sharethis.html.erb
<script type="text/javascript">var switchTo5x=true;</script><script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script><script type="text/javascript">stLight.options({publisher:'47d50acc-bbf5-473f-af02-4f5b486f3ce6'});</script>

<span  class='st_twitter_vcount' displayText='Tweet'></span><span  class='st_email_vcount' displayText='Email'></span><span  class='st_facebook_vcount' displayText='Facebook'></span><span  class='st_fblike_vcount' ></span>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title><%= site_title %></title>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "public/application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Arapey:400italic|Lato:300,400,100|Stoke:400' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <!-- Adding "maximum-scale=1" fixes the Mobile Safari auto-zoom bug: http://filamentgroup.com/examples/iosScaleBug/ -->
  </head>
  <body lang="en">
    <header id="head">
      <div id="logo">Merrick Family Foundation</div>
      <span id="start-mission-quote">&#8220;</span>
      <div id="mission">The Merrick Family Foundation provides support and opportunities to children and young adults who have experienced unforeseen hardships in order to enhance their quality of life.</div>
      <span id="end-mission-quote">&#8221;</span>
      <div id="search">
        <form action="http://www.google.com/search" method="get">
        <input style="visibility:hidden" type="radio" name="sitesearch" value="merrickfamilyfoundation.org" checked="checked" /> 
        <input class="text-input" type="text" name="q">
        <input type="submit" class="button" value="SEARCH">
        </form>
      </div>
      <div id="donate">
        <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="hosted_button_id" value="WHRUSLW8237N2">
        <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
        <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
        </form>
      </div>
      <%= render :partial => 'nav', :object => page_links %>
    </header>

    <div id="content-wrapper">
      <div id="mainContent">
        <%= yield %>
      </div>
      <%= render :partial => 'aside', :object => posts %>
    </div>
    <%= render :partial => 'footer', :object => page_links %>

  </body>
</html>

app/views/messages/_apply.html.erb
<h2>Coming Soon</h2>

app/views/messages/_contact.html.erb
<h2>Contact Us</h2>
 <%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
  <div id="errorExplanation">
    <span><%= pluralize(@message.errors.count, "error") %> prohibited this message from being sent:</span>
    <ul>
    <% @message.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label 'Name' %><br />
    <%= f.text_field :from_name %>
  </div>

  <div class="field">
    <%= f.label 'Email' %><br />
    <%= f.text_field :from_email %>
  </div>
 
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <%= f.hidden_field :form_name %>
  <div class="actions">
    <%= f.submit 'SEND', :class => 'button' %>
  </div>
<% end %>

app/views/messages/_contact_form.html.erb
<h2>Contact Us</h2>
 <%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
  <div id="errorExplanation">
    <span><%= pluralize(@message.errors.count, "error") %> prohibited this message from being sent:</span>
    <ul>
    <% @message.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label 'Name' %><br />
    <%= f.text_field :from_name %>
  </div>

  <div class="field">
    <%= f.label 'Email' %><br />
    <%= f.text_field :from_email %>
  </div>
 
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit 'SEND', :class => 'button' %>
  </div>
<% end %>

app/views/messages/create.html.erb
<div id="article-wrapper">
	<h2>Thank You</h2>
	<span>Thank you for contacting us. We appreciate your interest in the Merrick Family Foundation. We will get back to you shortly.</span>
</div>

app/views/messages/show.html.erb
<div id="article-wrapper">
	<%= render :partial => @message.form_name %>
</div>

app/views/messages/thank_you.html.erb
<div id="article-wrapper">
	<h2>Thank You</h2>
	<span>Thank you for contacting us. We appreciate your interest in the Merrick Family Foundation. We will get back to you shortly.</span>
</div>

app/views/pages/content.html.erb
<%= raw @page.content %>

app/views/posts/_aside.html.erb
<aside id="side-bar">
	<h2>Post Aside</h2>
	<div class="widget-container" id="sharethis-widget">
		<%= render :partial => 'sharethis' %>		
	</div> 
	
</aside>

app/views/posts/index.html.erb
<div id="article-wrapper">
	
	<% @posts.each do |post| %>
	<article>
	    <h2><%= post.title %></h2>
	    <%= post.content %>
	</article>
	<% end %>

</div>

app/views/posts/show.html.erb
<div id="article-wrapper">
	<article>
	<h2><%= @post.title %></h2>
	<%= @post.content %>
	</article>
</div>